I. INTRODUCTION

Installation:
- Step 1: Open Terminal
- Step 2: Locate the folder using the cd command where the python-pip file has been installed
- Step 3: After locating, type the command:
        pip install pandas

    - There are 2 data structures for manipulating data. They are:
- Series
- DataFrame

    - Creating a Series

- A Pandas Series is a one-dimensional labeled array capable of hodling data of any type.

In [3]:
import pandas as pd 
import numpy as np

# Creating empty series 
ser = pd.Series() 
print("Pandas Series: ", ser) 

# simple array 
data = np.array(['g', 'e', 'e', 'k', 's']) 
  
ser = pd.Series(data) 
print("Pandas Series:\n", ser)

Pandas Series:  Series([], dtype: object)
Pandas Series:
 0    g
1    e
2    e
3    k
4    s
dtype: object


In [6]:
import pandas as pd
#Creating Series from a list
s = pd.Series([1,3,5,7,8])
print(s)
#Creating Series with custom index
s_custom_index = pd.Series([10,20,30], index = ['a','b','c'])
print(s_custom_index)

0    1
1    3
2    5
3    7
4    8
dtype: int64
a    10
b    20
c    30
dtype: int64


In [11]:
#Creating a Series from Dictionaries
import pandas as pd

# a simple dictionary
dict = {'Geeks': 10,
		'for': 20,
		'geeks': 30}

# create series from dictionary
ser = pd.Series(dict)

print(ser)


Geeks    10
for      20
geeks    30
dtype: int64


    - Pandas DataFrame

- Pandas DataFrame is a two-dimensional data structure with labeled axes (rows and columns) 

In [4]:
import pandas as pd
#Calling DataFrame constructor
df = pd.DataFrame()
print(df)
#list of strings
lst = ['Thuc','Tap','Sinh','AIOT']
#Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)

Empty DataFrame
Columns: []
Index: []
      0
0  Thuc
1   Tap
2  Sinh
3  AIOT


In [8]:
#Creating DataFrame from a dictionary column
data = {
    'Name' : ['John','Anna','Peter', 'Linda'],
    'Age' : [28,24,35,34],
    'City' :[ 'New York', 'Paris ', 'Berlin', 'London']
}
df = pd.DataFrame(data)
print(df)


    Name  Age      City
0   John   28  New York
1   Anna   24    Paris 
2  Peter   35    Berlin
3  Linda   34    London


II. READING FILES WITH OPEN 


1. Using Open()

- is a tool opening files in Python. It receives two main parameters: the file's name and the open file mode

Common files open mode: 
- 'r': Open files for reading only (default)
- 'w': Open files for writing only (if the file exists, the old content will be overwritten, if the file does not exist, a new file will be created)
- 'a': Opens the the file for writing, appending content to the end of the file if it already exists
- 'b': Opens the file in binary mode (used in combination with other modes, e.g. 'rb' for reading binary files)
- 'r+': Opens the file for both reading and writing

In [13]:
#Syntax: file_object = open('filename',mode)
# Mở file để đọc
file = open('data.txt', 'r')

# Đọc toàn bộ nội dung file
content = file.read()

# In ra nội dung
print("Toàn bộ nội dung file:")
print(content)

# Đóng file
file.close()


Toàn bộ nội dung file:
Hello, world!
Python is great.
OpenAI develops ChatGPT.



- file.read() reads the entire content of the file and stores it in the variable 'content'
- the 'print(content) statement then ptrints the entire content of the file


    - Reading the File line by line

In [6]:
# Open the file for reading
file = open('data.txt', 'r')

# Read the file line by line
print("\nReading the file line by line:")
line = file.readline()
while line:
    print(line, end='')  # `end=''` to avoid adding extra new lines
    line = file.readline()

# Close the file
file.close()


    - Reading All Lines into a List

In [ ]:
# Open the file for reading
with open('data.txt', 'r') as file:
    lines = file.readlines()

# Print the list of lines
print("\nList of lines in the file:")
for line in lines:
    print(line, end='')


    - Using 'with' to Ensure the File is Always closed

In [ ]:
# Open the file for reading with 'with'
with open('data.txt', 'r') as file:
    content = file.read()
    print("\nFile content using 'with':")
    print(content)


    - Handling Errors when Opening Files

In [ ]:
try:
    # Attempt to open a non-existent file
    file = open('nonexistentfile.txt', 'r')
    content = file.read()
    print(content)
except FileNotFoundError:
    print("\nError: File not found.")
except IOError:
    print("\nError: Unable to read the file.")

III. WRITING FILES WITH OPEN 

1. Using the 'open()' Function to Write Files

- The 'open()' function is used top open files in Python. When writing to a file, you need to specify the appropriate mode:
- Common modes for writing files:
    - 'w': Opens a file for writing. If the file already exists, its contents will be overwritten. If the file does not exist, a new file will be created.
    - 'a': Opens a file for appending. New data will be added to the end of the file without overwriting the existing content. If the file does not exist, a new file will be created.
    - 'w+': Opens a file for both reading and writing. If the file exists, its contents will be overwritten.
    - 'a+': Opens a file for both reading and writing, with new data being added to the end of the file.

2. Writing Data to a File

a. Writing a String to a File

In [4]:
# Open a file for writing
file = open('output.txt', 'w')

# Write a string to the file
file.write("Hello, world!\n")
file.write("Python is great.\n")

# Close the file
file.close()


b. Writing Multiple Lines to a File

In [5]:
# Open a file for writing
with open('output.txt', 'w') as file:
    lines = ["Hello, world!\n", "Python is great.\n", "OpenAI develops ChatGPT.\n"]
    file.writelines(lines)


c. Appending to a File without Overwriting 


In [6]:
# Open a file to append data
with open('output.txt', 'a') as file:
    file.write("This line is appended to the file.\n")


3. Writing Binary Files

In [ ]:
# Write binary data to a file
with open('images.jpg', 'wb') as file:
    file.write(binary_data)


- Open the file in 'wb' mode to write binary data. This is typically used for non-text files like images or audio.
- 'binary data' is the binary data that you want to the file

4. Handling Errors when Writing Files

In [18]:
try:
    with open('readonlyfile.txt', 'w') as file:
        file.write("Attempting to write to a read-only file.")
except IOError:
    print("An error occurred trying to write to the file.")


IV. PANDAS LOADING DATA

1. Loading CSV Files

- CSV(Comma-Separated Values) is one of the most common data formats. You can load a CSV file into a Pandas DataFrame using the 'read_csv()' function.

In [ ]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('data.csv')

# Display the first 5 rows of the DataFrame
print(df.head())


- Parameters:
    - filepath_or_buffer: The file path to the CSV file.
    - sep: The delimiter (default is a comma ,).
    - header: Row number(s) to use as the column names.
    - names: List of column names to use.

2. Loading Excel Files

- Excel files can also be loaded into a Pandas DataFrame using the 'read_excel()' function.

In [ ]:
df = pd.read_excel('data.xlsx', sheet_name = 'Sheet1')
#Display the first 5 rows of the DataFrame
print(df.head())

- Parameters:
    - 'io': The file path to the Excel file.
    - 'sheet_name': The sheet name or sheet number to load.

3. Loading JSON Files

- JSON (JavaScript Object Notation) is lightweight data interchange format. You can load JSON data into a Pandas DataFrame using the 'read_json()' function.

In [19]:
df = pd.read_json('data.json')

# Display the first 5 rows of the DataFrame
print(df.head())

NameError: name 'pd' is not defined

- Parameters
    - 'path_or_buf': The file path to the JSON file or a JSON string.

4. Loading SQL Databases.

- Pandas can directly interact with SQL databases using the 'read_sql()' function.

In [ ]:
import sqlite3

# Create a connection to the database
conn = sqlite3.connect('database.db')

# Load data from SQL query into a DataFrame
df = pd.read_sql('SELECT * FROM tablename', conn)

# Display the first 5 rows of the DataFrame
print(df.head())


5. Loading Data from a URL

- You can also load data directly from a URL, which is especially useful for working with public datasets.

In [ ]:
url = 'https://example.com/data.csv'
df = pd.read_csv(url)

# Display the first 5 rows of the DataFrame
print(df.head())


- Common Data Loading Options
    - Handling Missing Values: You can specify how missing values should be handled during data loading by using parameters like na_values or keep_default_na.
    - Specifying Data Types: Use the dtype parameter to specify the data type for each column.
    - Chunksize: Load data in chunks (useful for large datasets that can't be loaded into memory at once).
- These examples cover the basic methods for loading data into a Pandas DataFrame, which is the first step in any data analysis or manipulation task. Once the data is loaded into a DataFrame, you can perform a wide range of operations on it, such as cleaning, transforming, and analyzing the data.

5. Working with and Saving Data

- Pandas is an essential Python library for data manipulation and analysis. Once you've loaded your data into a Pandas DataFrame, there are a variety of operations you can perform to clean, transform, analyze, and ultimately save the data.

1. Viewing data

- Head and Tail: To quickly view the first or last few rows of a DataFrame

In [ ]:
df.head()  # Shows the first 5 rows by default
df.tail()  # Shows the last 5 rows by default


2. Selecting Data

- Selecting Columns: You can select one or more columns from a DataFrame.

In [ ]:
df['column_name']  # Selects a single column
df[['column1', 'column2']]  # Selects multiple columns


Selecting Rows: You can select rows based on their index using .loc[] or .iloc[].

In [ ]:
df.loc[0]  # Selects the first row by label
df.iloc[0]  # Selects the first row by position


3. Filtering Data

- Conditional Selection: You can filter data based on conditions

In [24]:
df[df['column_name'] > value]  # Selects rows where the condition is true


4. Adding New Columns

- You can add new columns based on existing data

In [23]:
df['new_column'] = df['column1'] + df['column2']


5. Handling Missing Data

- Fill Missing Values: Fill missing values with a specific value or a strategy (mean, median, etc.).

In [ ]:
df['column_name'].fillna(value, inplace=True)


- Drop Missing Values: Remove rows or columns that contain missing data

In [ ]:
df.dropna(inplace=True)


6. Grouping Data

- Group By: Group data and apply aggregate functions like mean, sum, count, etc.

In [ ]:
df.groupby('column_name').sum()


7. Sorting Data

- Sorting: Sort the DataFrame by one or more columns

In [ ]:
df.sort_values(by='column_name', ascending=False)


    - SAVING DATA

1. Saving to CSV

- Save the DataFrame to a CSV file.

In [ ]:
df.to_csv('output.csv', index=False)


- Parameters:
    - path_or_buf: File path or object, if None is provided, the result is returned as a string.
    - sep: String of length 1, Field delimiter for the output file (default is a comma).
    - index: If False, do not write row names (index).

2. Saving to Excel

- Save the DataFrame to an Excel file.

In [ ]:
df.to_excel('output.xlsx', sheet_name='Sheet1', index=False)

- Parameters:
    - excel_writer: File path or existing ExcelWriter.
    - sheet_name: Name of the sheet in the Excel file where the DataFrame will be saved.
    - index: If False, do not write row names (index).

3. Saving to JSON 

- Save the DataFrame to a JSON file.

In [ ]:
df.to_json('output.json')


- Parameters:
    - path_or_buf: File path or object to write.
    - orient: The format in which the JSON should be saved ('split', 'records', 'index', 'columns', 'values').

4. Saving to SQL.

- You can also save data to a SQL database using Pandas.

In [ ]:
from sqlalchemy import create_engine

engine = create_engine('sqlite:///:memory:')
df.to_sql('table_name', engine)


- Parameters:
    - name: Name of the table to write.
    - con: Connection to the database.

V. ONE DIMENSIONAL NUMPY

1. Creating a One-Dimensional Array

- Creating an array from a Python list:

In [26]:
import numpy as np
#Create a one-dimensional array from a list
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


    - 'np.array()' converts a Python list into a Numpy one-dimensional array.

- Using Numpy's array creation functions:

-'np.zeros()': Creates an array filled with zeros.

In [27]:
arr = np.zeros(5)
print(arr)


[0. 0. 0. 0. 0.]


- 'np.arrange()': Creates an array with a range of values.

In [28]:
arr = np.arange(0, 10, 2)  # From 0 to <10, step by 2
print(arr)


[0 2 4 6 8]


'np.linspace()': Creates an array with evenly spaced values over a specified interval.

In [29]:
arr = np.linspace(0, 1, 5)  # 5 values from 0 to 1
print(arr)


[0.   0.25 0.5  0.75 1.  ]


2. Accessing and Manipulating a One-Dimensional Array

- Accessing elements:

In [30]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])  # Access the first element
print(arr[-1])  # Access the last element

1
5


- Slicing

In [31]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # Access elements from index 1 to <4
print(arr[:3])   # Access the first 3 elements
print(arr[3:])   # Access elements from index 3 to the end


[2 3 4]
[1 2 3]
[4 5]


- Modifyinh values

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 10  # Change the first element to 10
print(arr)

3. Operations on a One-Dimensional Array

- Basic arithmetic operations:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Add 1 to all elements
print(arr + 1)

# Multiply all elements by 2
print(arr * 2)

# Sum of all elements
print(np.sum(arr))

# Mean of all elements
print(np.mean(arr))


Operations between arrays:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add two arrays
print(arr1 + arr2)

# Multiply two arrays
print(arr1 * arr2)


4. Useful Functions for One-Dimensional Arrays.

- Finding the maximum and minimum values

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Add two arrays
print(arr1 + arr2)

# Multiply two arrays
print(arr1 * arr2)


- Finding the index of an element

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr == 3))  # Find the index of the element with value 3


- Reversing an array

In [33]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[::-1])  # Reverse the array


[5 4 3 2 1]


5. Type Conversion

In [ ]:
arr = np.array([1.1, 2.2, 3.3])
arr = arr.astype(int)  # Convert all elements to integers
print(arr)


- Changing the data type of an array

VI. TWO DIMENSIONAL NUMPY

1. Creating a Two-Dimensional Array

In [34]:
import numpy as np

# Create a 2D array from a nested list
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


- 'np.eye(N)': Creates an identity matrix of size NxN

In [38]:
arr = np.eye(3)  # A 3x3 identity matrix
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Accessing and Manipulating a Two-Dimensional Array

- Accessing elements:

In [39]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0, 0])  # Access the element at row 0, column 0
print(arr[1, 2])  # Access the element at row 1, column 2


1
6


- Slicing (Subsetting the array):

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr[0:2, 1:3])  # Access elements from row 0 to <2 and column 1 to <3


[[2 3]
 [5 6]]


- Modifying values:

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr[0, 0] = 10  # Change the first element to 10
print(arr)


[[10  2  3]
 [ 4  5  6]
 [ 7  8  9]]


3. Operations on a Two-Dimensional Array

- Basic operations across the entire array:

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Sum of all elements
print(np.sum(arr))

# Mean of all elements
print(np.mean(arr))

# Sum across rows and columns
print(np.sum(arr, axis=0))  # Sum along columns
print(np.sum(arr, axis=1))  # Sum along rows


45
5.0
[12 15 18]
[ 6 15 24]


- Operations between arrays:

In [44]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

# Add arrays
print(arr1 + arr2)

# Multiply arrays
print(arr1 * arr2)


[[ 8 10 12]
 [14 16 18]]
[[ 7 16 27]
 [40 55 72]]


- Matrix operations:

In [45]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Dot product between two matrices
print(np.dot(arr1, arr2))



[[19 22]
 [43 50]]


4. Useful Functions for Two-Dimensional Arrays


- Transpose the matrix:

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)  # Or use arr.transpose()


[[1 4]
 [2 5]
 [3 6]]


- Reshape the array

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
new_arr = arr.reshape(3, 2)  # Reshape from 2x3 to 3x2
print(new_arr)


[[1 2]
 [3 4]
 [5 6]]


- Flatten the array

In [49]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr = arr.flatten()  # Convert a 2D array into a 1D array
print(flat_arr)


[1 2 3 4 5 6]


5. Filtering and Conditional Operations on Two-Dimensional Arrays

- Filtering arrays with conditions:

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[arr > 3])  # Filter elements greater than 3


[4 5 6]


- Using np.where to filter and replace values:

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.where(arr > 3, arr, 0)  # Keep elements greater than 3, replace others with 0
print(result)


[[0 0 0]
 [4 5 6]]
